### ISSUE TITLE
Automatically use build credentials for download

### ISSUE THREAD

**Issue by jonnyzzz** [jk1/TeamCity-dependencies-gradle-plugin#24]
There is no option to setup credentials that are used for all queries to TeamCity.

It'd be nice to make plugin use build credentials automatically without any setup.

**Comment by nskvortsov** [comment]
At the moment, credentials can be set like this: 
```

repositories {
  teamcityServer {
    url = "http://url.to.team.city/"
    credentials {
      username = teamcity_username
      password = teamcity_password
    }
  }
```

**Comment by jonnyzzz** [comment]
How do I get the build credentials there?

**Comment by jk1** [comment]
@jonnyzzz what's a "build credentials"? I don't recall anything like that in Gradle.

**Comment by jonnyzzz** [comment]
The trick is that when you run a build on TeamCity, there is a build-specific account. Credentials can be inferred from build properties. The best way is to use those credentials to fetch dependencies. Once implemented, TeamCity service will track a dependency was downloaded. 
The only thing is we have to have at least a HEAD query from every build, no matter if something was cached

**Comment by jk1** [comment]
Not sure what the problem is then:

```
repositories {
  teamcityServer {
    url = "http://url.to.team.city/"
    credentials {
      username = teamcity['login.build.property']
      password = teamcity['password.build.property']
    }
  }
```

**Comment by jonnyzzz** [comment]
It should be (as @nskvortsov wrote) 
```
teamcity.auth.userId
teamcity.auth.password
```
https://confluence.jetbrains.com/display/TCD10/Predefined+Build+Parameters#PredefinedBuildParameters-ServerBuildProperties

I missed the thing you have `credentials` configuration element

**Comment by jk1** [comment]
So there're conventionally named credentials defined by TC itself. That makes much more sense now, thanks for suggestion.
