### ISSUE TITLE
Patterns in artifact name are no longer works 

### ISSUE THREAD

**Issue by VladRassokhin** [jk1/TeamCity-dependencies-gradle-plugin#32]
Seems [somewhere between 0.9.1 and 0.12](https://github.com/jk1/TeamCity-dependencies-gradle-plugin/compare/0.9.1...0.12) patterns in file names stopped working.  
Configuration: `"ijplatform_IjPlatform172_Idea_InstallersForEapRelease:172.3317.76:ideaIU.*-teamcity.zip"`

Gradle 4.2.1 output with plugin versions 0.12 - 0.16:
```text
* What went wrong:
Could not determine the dependencies of task ':prepareIdeaJdk16'.
> Could not resolve all files for configuration ':idea_jdk16_fixed'.
   > Could not find ideaIU.*-teamcity.zip (org:ijplatform_IjPlatform172_Idea_InstallersForEapRelease:172.3317.76).
     Searched in the following locations:
         http://server/httpAuth/repository/download/ijplatform_IjPlatform172_Idea_InstallersForEapRelease/172.3317.76/ideaIU.*-teamcity.zip
```

**Comment by jk1** [comment]
So I have checked it with the following simple configuration with the same file:
```groovy
repositories {
    teamcityServer {
        url = '***'
        credentials {
            username = '***'
            password = '***'
        }
    }
}

dependencies {
    compile tc('ijplatform_IjPlatform172_Idea_InstallersForEapRelease:172.3317.76:ideaIU.*-teamcity.zip')
}

task listDeps {
    doLast {
        configurations.compile.each {
            dep -> println(dep)
        }
    }
}
```
And here's what I've found:

- It works without issues on Gradle 4.2 with plugin 0.15.
- It doesn't work on Gradle 4.3 with plugin 0.16, as [gradle team introduced](https://docs.gradle.org/current/release-notes.html#timeouts-for-http/https-requests) an artifact resolution timeout of 10s. And indeed, it looks like TeamCity server requires 20 seconds to handle us ivy.xml alone and the same amount of time to start the actual file download.
- It works on Gradle 4.3.1 with plugin 0.16. Artifact resolution timeout has been increased to 30 seconds in Gradle 4.3.1 and that's enough for TeamCity to respond.

Hope that helps.

**Comment by VladRassokhin** [comment]
Thanks, that's kind of weird issue, will try again next week (after release)

**Comment by VladRassokhin** [comment]
Checked Gradle 4.3.1 and plugin 0.16 and next configuration doesn't work:
```
repositories {
    teamcityServer {
        url = '***'
        credentials {
            username = '***'
            password = '***'
        }
    }
}
configurations {idea}
dependencies {
    idea tc('ijplatform_IjPlatform172_Idea_InstallersForEapRelease:172.3317.76:ideaIU.*-teamcity.zip')
}

task unpack(type:Sync) {
  from { zipTree(configurations.idea.singleFile) }
  into "$root/idea"
}
```

**Comment by VladRassokhin** [comment]
Same with Gradle 4.5.1 and plugin 0.17 :(
Please reopen issue

**Comment by VladRassokhin** [comment]
Ok, seems it finally works with plugin 0.17 and Gradle 4.7 for following configuration:
```

plugins {
    id 'com.github.jk1.tcdeps' version '0.17'
}

apply plugin: 'base'

repositories {
    teamcityServer {
        url = "http://localhost:8111/"
    }
}

ext {
    root = file(project.projectDir)
}
configurations {
    arts
}

dependencies {
    arts tc("GradleTeamCityDepsPluginDemo_SomeAttifacts:lastSuccessful:ar(.*).zip")
}
def stripVersion(cfg){
    {
        name ->
            def artifacts = cfg.resolvedConfiguration.resolvedArtifacts
            def artifact = artifacts.find { it.file.name == name }
            name - "-${artifact.moduleVersion.id.version}"
    }
}

task prepareArtsRename(type: Sync) {
    from { configurations.arts.files }
    rename stripVersion(configurations.arts)
    into "$root/fetched/renamed"
}

task prepareArtsRaw(type: Sync) {
    from { configurations.arts.singleFile }
    into "$root/fetched/raw"
}
```
I think initial problem was around `from { configurations.arts.files }` vs `from configurations.arts`
