### ISSUE TITLE
Ignores credentials when getting build number

### ISSUE THREAD

**Issue by rocketraman** [jk1/TeamCity-dependencies-gradle-plugin#38]
It looks like this ignores the set TC credentials in certain situations.

For example, when obtaining a build number it always uses `guestAuth`:

https://github.com/jk1/TeamCity-dependencies-gradle-plugin/blob/master/src/main/groovy/com.github.jk1.tcdeps/client/RequestBuilder.groovy#L48

This makes it unusable for me: my TeamCity does not allow guest connections.

**Comment by jk1** [comment]
Thanks for reporting it. 
I would agree that this request should reuse configured credentials.
