### ISSUE TITLE
Support of TC branches

### ISSUE THREAD

**Issue by msenin** [jk1/TeamCity-dependencies-gradle-plugin#4]
Need possibility to specify branch of build.
Example of getting build number of last successful build number for given buildTypeId and buildBranch: http://buildserver.somesite.com/guestAuth/app/rest/builds/buildType:<buildTypeId>,branch:<buildBranch>,status:SUCCESS/number"

See https://confluence.jetbrains.com/display/TCD9/REST+API#RESTAPI-BuildLocator

**Comment by jk1** [comment]
Implemented in 0.6
