### ISSUE TITLE
Credentials do not work   

### ISSUE THREAD

**Issue by pell-je** [jk1/TeamCity-dependencies-gradle-plugin#46]
Does this use the underlying team city REST API?

I am getting 401.. "Allow login as guest user" needs to be turned off

```
    teamcityServer {
        url = 'https://<domain>.teamcity.com/'
        credentials(HttpHeaderCredentials) {
            name = "Authorization"
            value = "Bearer <token>"
        }
        authentication {
            header(HttpHeaderAuthentication)
        }
    }

```
I also tried:

```
        credentials {
            username = "user"
            password = "pass"
        }
```

How do I authenticate into the team city server with guest login turned off?
Something like above?

```

Server response: 
 com.github.jk1.tcdeps.client.RestClient$Response(401, An error in configuration or an internal error occurred during login. Please contact your system administrator.

[To login manually go to "/login.html" page, false)](url)
```

**Comment by pell-je** [comment]
```
Server response: 
 com.github.jk1.tcdeps.client.RestClient$Response(401, An error in configuration or an internal error occurred during login. Please contact your system administrator.
```

**Comment by pell-je** [comment]
[To login manually go to "/login.html" page, false)](url)

**Comment by jk1** [comment]
Hi there.

Yes, the following should be enough

```
credentials {
    username = "user"
    password = "pass"
 }
```
As an alternative one can also use

```
pin {
      username = "user"
      password = "pass"
}

```

I'm not so well versed in TeamCity, but the error message `An error in configuration or an internal error occurred during login` suggests a configuration error on TeamCity side. You may try to login with curl to see if it works.

**Comment by pell-je** [comment]
yes I can log in via curl.

Im thinking it sends out a request with guestAuth instead of httpAuth?

How can I log the calls the api makes?

Both pin and credentials same error

version '1.3'


To confirm where should he pin block be inside the teamcityServer block?

I cloned repo and testing locally

**Comment by pell-je** [comment]
#38

**Comment by pell-je** [comment]
`private void authenticate(HttpURLConnection connection, Authentication auth) {}`

`auth.isRequired()` retruns false

when 

```
credentials {
    username = "user"
    password = "pass"
 }
```

**Comment by pell-je** [comment]
```

    String baseUrl
    Closure uriPath
    BuildLocator locator

    Authentication authentication = new Authentication()
    String body

    String toString(){
        if (!baseUrl || !uriPath || !locator){
            throw new IllegalArgumentException("Base url, path and locator should be specified")
        }
        "$baseUrl${uriPath.call(locator, authentication.isRequired())}"
    }
```

A new Authentication object is created with login and password always null

**Comment by pell-je** [comment]
I think its because a new Authentication authentication = new Authentication() object is created each time and  below methods are never called

   ```
 void login(String login) {
        request.authentication.login = login
    }

    void password(String password) {
        request.authentication.password = password
    }
```

**Comment by pell-je** [comment]
also `getConfiguredCredentials().isPresent():` returns false with `credentials  `and or `pin `config

**Comment by pell-je** [comment]
ConfigureUtil.configure is depracted not sure if that matters

**Comment by pell-je** [comment]
I looked into this more..

the credentials is loaded properly for getting the build number because its loaded from

 `repo.&credentials`

and 

`repo.metaClass.credentials`


but actually downloading  the artifact fails because  `login()` & `password() `are never called in `RequestBuilder`

**Comment by jk1** [comment]
Thank you for taking a closer look.
I should be able to fix it this week.

**Comment by jk1** [comment]
I did some testing with TeamCity cloud. It seems that credentials are respected most of the time. It's only placeholder resolution that's broken. So `lastFinished` or `lastPinned` can't be resolved w/o guest auth enabled, while wtih the exact build number everything's fine:

`implementation tc('CiIntegrationTest_Build:2:README.md')`

**Comment by pell-je** [comment]
> I did some testing with TeamCity cloud. It seems that credentials are respected most of the time. It's only placeholder resolution that's broken. So `lastFinished` or `lastPinned` can't be resolved w/o guest auth enabled, while wtih the exact build number everything's fine:
> 
> `implementation tc('CiIntegrationTest_Build:2:README.md')`
 
Thank you for clarification.

**Comment by jk1** [comment]
@pell-je please give version 1.4 a try, it should have the bug fixed.
I've also updated the documentation examples to clarify auth configuration details.

**Comment by pell-je** [comment]
ok i think i need to wait for it to be approved on gradle plugins site. Or something.

```
Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.github.jk1:tcdeps-kt:1.4.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/github/jk1/tcdeps-kt/1.4/tcdeps-kt-1.4.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project : > com.github.jk1.tcdeps:com.github.jk1.tcdeps.gradle.plugin:1.4 > gradle.plugin.com.github.jk1:tcdeps:1.4
   > Could not find com.github.jk1:tcdeps-groovy:1.4.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/github/jk1/tcdeps-groovy/1.4/tcdeps-groovy-1.4.pom
     If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
     Required by:
         project : > com.github.jk1.tcdeps:com.github.jk1.tcdeps.gradle.plugin:1.4 > gradle.plugin.com.github.jk1:tcdeps:1.4

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html 
```

**Comment by jk1** [comment]
It seems that everything is resolvable now
